from typing import TypedDict, Annotated, List
import operator


class Text2ChartState(TypedDict):
    user_query: Annotated[List[str], "user queries in recieved order", operator.add]

    rewrite_query: Annotated[str, "rewrited query by the LLM", operator.add]

    dataframe_code: Annotated[str, "dataframe code generated by the LLM"]

    chart_generation_code: Annotated[str, "chart generation code generated by the LLM"]

    code_error: Annotated[str, "code error that occurred when executing the code generated by the LLM", operator.add]

    code_output: Annotated[str, "code output that occurred when executing the code generated by the LLM", operator.add]

    img_path: Annotated[str, "file path of the chart image", operator.add]

    img_bytes: Annotated[bytes, "byte date of the chart image", operator.add]

    chart_desc: Annotated[str, "description of chart generated by the LLM", operator.add]

    prev_node: Annotated[str, "name of the previous node in the workflow(agent)"]