from typing import TypedDict, Annotated
import operator


class Text2ChartState(TypedDict):
    user_query: Annotated[str, "entered user_query"]

    rewrite_query: Annotated[str, "rewrited query by the LLM"]

    code: Annotated[str, "python code for the chart generated by the LLM"]

    code_error: Annotated[str, "code error that occurred when executing the code generated by the LLM"]

    img_path: Annotated[str, "file path of the chart image"]

    img_bytes: Annotated[bytes, "byte date of the chart image"]

    chart_desc: Annotated[str, "description of chart generated by the LLM"]

    prev_node: Annotated[str, "name of the previous node in the workflow(agent)"]